name: Init the project from template

on:
  push:
    branches: main

permissions: write-all

jobs:
  rename-project:
    if: github.repository != 'lublak/n8n-nodes-base'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - id: init_exists
        uses: andstor/file-existence-action@v1
        with:
          files: init.js
      - name: run init.js
        if: steps.init_exists.outputs.files_exists == 'true'
        run: node init.js && rm -fr init.js && rm -fr .github/workflows/init.yml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "init"
          push_options: --force
